FROM node:16-alpine as react-build
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY --from=react-build /app/build /usr/share/nginx/html